name: Client CD Pipeline

on:
  workflow_run:
    workflows: ["Client CI Pipeline"]
    types:
      - completed

      
jobs:

  build:

    runs-on: self-hosted 

    steps:
    - name: Pull docker image
      run: sudo docker pull lukaneek/clientserver-client:latest
    - name: Delete old docker container
      run: sudo docker rm -f clientserver-client || true
    - name: Run docker container
      run: sudo docker run -d -p 80:80 --name clientserver-client lukaneek/clientserver-client