name: Server CD Pipeline

on:
  workflow_run:
    workflows: ["Server CI Pipeline"]
    types:
      - completed

      
jobs:

  build:

    runs-on: self-hosted 

    steps:
    - name: Pull docker image
      run: sudo docker pull lukaneek/clientserver-server:latest
    - name: Delete old docker container
      run: sudo docker rm -f clientserver-server || true
    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name clientserver-server lukaneek/clientserver-server