name: Server CI Pipeline

on:
  push:
    branches: 
      - main
    paths:
      - 'server/**'

jobs:

  build:

    defaults:
      run:
        working-directory: server

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t lukaneek/clientserver-server:latest .
    - name: Push to Dockerhub
      run: docker push lukaneek/clientserver-server:latest
    